version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/mounteam
permissions:
  - object: /home/ubuntu/mounteam/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: /home/ubuntu/deploy.sh
      timeout: 60
      runas: ubuntu