config:
#  type: aws-parameterstore:/Mounteam/BE/

spring:
#  config:
#    import: aws-parameterstore:/Mounteam/BE/
  profiles:
    active:
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS-HOSTNAME}:${RDS_PORT}/${RDS-DB-NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS-USERNAME}
    password: ${RDS-PASSWORD}

oauth2:
  kakao:
    client_id: ${OAUTH-CLIENT-ID}
    client_secret: ${OAUTH-SECRET-ID}
    authorization_grant_type: authorization_code
    redirect_uri: "http://localhost:3000/oauth/kakao"
    client_authentication_method: client_secret_post
  provider:
    authorizationUri: https://kauth.kakao.com/oauth/authorize
    tokenUri: https://kauth.kakao.com/oauth/token
    userInfoUri: https://kapi.kakao.com/v2/user/me
    userNameAttribute: id

jwt:
  token:
    secret-key: ${JWT_TOKEN}

awsParameterStorePropertySource:
  enabled: true