config:
  type: aws-parameterstore:/Mounteam/BE/

spring:
  config:
    import: aws-parameterstore:/Mounteam/BE/
  profiles:
    active:
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS-HOSTNAME}:${RDS_PORT}/${RDS-DB-NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS-USERNAME}
    password: ${RDS-PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
jwt:
  token:
    secret-key: ${JWT_TOKEN}
oauth2:
  kakao:
    client_id: ${OAUTH-CLIENT-ID}
    client_secret: ${OAUTH-SECRET-ID}
    admin_id: ${OAUTH-ADMIN-ID}
    authorization_grant_type: authorization_code
    redirect_uri: ${KAKAO_REDIRECT}
    client_authentication_method: client_secret_post
  provider:
    authorizationUri: https://kauth.kakao.com/oauth/authorize
    tokenUri: https://kauth.kakao.com/oauth/token
    userInfoUri: https://kapi.kakao.com/v2/user/me
    userNameAttribute: id
cloud:
  aws:
    s3:
      bucket: mounteam-image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${MY-ACCESS-KEY}
      secretKey: ${MY-SECRET-KEY}

awsParameterStorePropertySource:
  enabled: true